# MicroZohm minimal (vivado2) - recorte de las constraints originales de mz-sw/vivado/constraints/te0808_mz
# Solo se conservan los puertos que existen en el block design minimo.
# D1: compuertas AXI_PWM_0 (D1_OUT[23:0]) + patron de habilitacion del Safety CPLD (26..29)
set_property PACKAGE_PIN AF3   [get_ports {D1_OUT[0]}]
set_property PACKAGE_PIN AG3   [get_ports {D1_OUT[1]}]
set_property PACKAGE_PIN AK3   [get_ports {D1_OUT[2]}]
set_property PACKAGE_PIN AK4   [get_ports {D1_OUT[3]}]
set_property PACKAGE_PIN AK7   [get_ports {D1_OUT[4]}]
set_property PACKAGE_PIN AK6   [get_ports {D1_OUT[5]}]
set_property PACKAGE_PIN AJ2   [get_ports D1_OUT[6]]
set_property PACKAGE_PIN AK2   [get_ports D1_OUT[7]]
set_property PACKAGE_PIN AH2   [get_ports D1_OUT[8]]
set_property PACKAGE_PIN AH3   [get_ports D1_OUT[9]]
set_property PACKAGE_PIN AE4   [get_ports D1_OUT[10]]
set_property PACKAGE_PIN AD4   [get_ports D1_OUT[11]]
set_property PACKAGE_PIN AC1   [get_ports D1_OUT[12]]
set_property PACKAGE_PIN AD1   [get_ports D1_OUT[13]]
set_property PACKAGE_PIN AC4   [get_ports D1_OUT[14]]
set_property PACKAGE_PIN AB4   [get_ports D1_OUT[15]]
set_property PACKAGE_PIN AC3   [get_ports D1_OUT[16]]
set_property PACKAGE_PIN AB3   [get_ports D1_OUT[17]]
set_property PACKAGE_PIN AA3   [get_ports D1_OUT[18]]
set_property PACKAGE_PIN AA2   [get_ports D1_OUT[19]]
set_property PACKAGE_PIN AE3   [get_ports D1_OUT[20]]
set_property PACKAGE_PIN AE2   [get_ports D1_OUT[21]]
set_property PACKAGE_PIN AD2   [get_ports D1_OUT[22]]
set_property PACKAGE_PIN AC2   [get_ports D1_OUT[23]]
set_property PACKAGE_PIN AG1   [get_ports {D1_OUT_26[0]}]
set_property PACKAGE_PIN AH1   [get_ports {D1_OUT_27[0]}]
set_property PACKAGE_PIN AA1   [get_ports {D1_OUT_28[0]}]
set_property PACKAGE_PIN AF2   [get_ports {D1_OUT_29[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports D1_*]
set_property PULLDOWN true [get_ports {D1_OUT[5]}]
set_property PULLDOWN true [get_ports {D1_OUT[4]}]
set_property PULLDOWN true [get_ports {D1_OUT[3]}]
set_property PULLDOWN true [get_ports {D1_OUT[2]}]
set_property PULLDOWN true [get_ports {D1_OUT[1]}]
set_property PULLDOWN true [get_ports {D1_OUT[0]}]
